Description: Cria grupo, funcao e politicas para engenheiro de dados

Resources:

  IamRoleDataEngineer:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument: #permite que qualquer usuario na aws
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              AWS: !Sub 'arn:aws:iam::${AWS::AccountId}:root' #vai substituir pelom numero da conta na aws
            Action:
              - sts:AssumeRole
      Description: Funcao para ser assumida por engenheiros de dados
      ManagedPolicyArns: #create a policy
        - !Ref IamPolicyDataEngineer
      RoleName: role-production-data-engineer # policy's name

  IamPolicyDataEngineer:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      Description: Politicas de acesso para engenheiro de dados
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Action:
              - s3:GetBucketLocation
              - s3:ListAllMyBuckets
              - s3:ListBucket
              - s3:GetObject
              - s3:PutObject
            Resource:
              - arn:aws:s3:::*

#creating a group for Data Engineer and a policy
  IamGroupDataEngineer:
    Type: AWS::IAM::Group
    Properties:
      GroupName: iam-group-data-engineer-2020
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/ReadOnlyAccess
        - !Ref IamPolicyGroupDataEngineer

  IamPolicyGroupDataEngineer:   #policy group, who is part of the group can assume that policy
    Type: AWS::IAM::ManagedPolicy
    Properties:
      Description: Politicas de acesso para o grupo de engenheiros de dados
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Action:
              - sts:AssumeRole
            Resource:
              - !GetAtt IamRoleDataEngineer.Arn  #metodo get amazon resources number
